---
- name: Déploiement de l'application avec Nginx
  hosts: webservers
  become: yes

  vars:
    app_dest: /var/www/html/tp-app
    nginx_conf_dest: /etc/nginx/sites-available/tp-app.conf
    nginx_conf_link: /etc/nginx/sites-enabled/tp-app.conf

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Créer le répertoire de destination
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers de l'application
      copy:
        src: ../app/
        dest: "{{ app_dest }}/"
        owner: www-data
        group: www-data
        mode: '0644'
        recurse: yes

    - name: Déployer la configuration Nginx via template
      template:
        src: nginx_vhost.conf.j2
        dest: "{{ nginx_conf_dest }}"
      notify: Restart nginx

    - name: Activer la configuration Nginx
      file:
        src: "{{ nginx_conf_dest }}"
        dest: "{{ nginx_conf_link }}"
        state: link

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
